[project]
name = "arch-maintainence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "readchar>=4.2.1",
    "rich>=14.0.0",
]
